/**
 * First-boot seeding, ported from app/seed.py.
 *
 * The Python app seeded itself on startup and wrote SECRETS.md next to the
 * code. A Worker has no filesystem and no startup hook that could hold
 * credentials, so seeding moved here: this runs on *your* machine, hashes the
 * passwords with the very code the Worker will later verify them with
 * (src/password.ts), writes SECRETS.md locally, and emits SQL for you to apply.
 *
 *   npm run seed              # writes seed.generated.sql + SECRETS.md
 *   npm run seed -- --local   # …and prints the --local apply command
 *
 * Both output files are gitignored. Nothing here ever runs in production.
 */

import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, appendFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { hashPassword } from "../src/password.ts";

const ITERATIONS = Number(process.env["PBKDF2_ITERATIONS"] ?? 100_000);
const SQL_FILE = resolve(import.meta.dirname, "..", "seed.generated.sql");
const SECRETS_FILE = resolve(import.meta.dirname, "..", "SECRETS.md");

// The HBPR URL comes from HBPR_URL so it can be re-pointed per environment.
const SEED_SITES = [
  {
    slug: "hbpr",
    name: "HBPR",
    url: process.env["HBPR_URL"] ?? "https://holbertonschoolpr.com/",
    description: "Holberton PR project site.",
    usesCfAccess: false,
  },
  {
    slug: "scholarship",
    name: "Holberton Scholarship",
    url: "https://scholarship.holbertonschoolpr.com/",
    description: "Scholarship application portal.",
    usesCfAccess: false,
  },
  {
    slug: "odoo",
    name: "Odoo — code.pr",
    url: "https://odoo.code.pr",
    description: "Odoo ERP, behind Cloudflare Access.",
    usesCfAccess: true,
  },
];

// Each client starts with one page. `sites` is ignored for the admin, who is
// unrestricted by rule rather than by assignment.
const SEED_USERS = [
  { username: "admin", fullName: "CodePR Administrator", isAdmin: true, sites: [] as string[] },
  { username: "user1", fullName: "Client User One", isAdmin: false, sites: ["hbpr"] },
  { username: "user2", fullName: "Client User Two", isAdmin: false, sites: ["scholarship"] },
  { username: "user3", fullName: "Client User Three", isAdmin: false, sites: ["odoo"] },
];

function generatePassword(): string {
  return randomBytes(12).toString("base64url");
}

/** Single-quote escaping for a SQL string literal. */
function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const local = process.argv.includes("--local");
  const now = new Date().toISOString();

  const lines: string[] = [
    "-- Generated by `npm run seed`. Contains password hashes — gitignored, do not commit.",
    `-- Generated ${now}`,
    "",
  ];

  // Only inserts what is missing, so re-running never overwrites a page an
  // admin has since re-pointed or an account whose password was rotated.
  for (const site of SEED_SITES) {
    lines.push(
      `INSERT OR IGNORE INTO sites (slug, name, url, description, is_active, uses_cf_access, created_at)`,
      `VALUES (${q(site.slug)}, ${q(site.name)}, ${q(site.url)}, ${q(site.description)}, 1, ${site.usesCfAccess ? 1 : 0}, ${q(now)});`,
      "",
    );
  }

  const created: Array<{ username: string; password: string; isAdmin: boolean }> = [];

  for (const spec of SEED_USERS) {
    const configured = spec.isAdmin
      ? process.env["SEED_ADMIN_PASSWORD"]
      : process.env["SEED_USER_PASSWORD"];
    const password = configured || generatePassword();
    const hash = await hashPassword(password, ITERATIONS);

    lines.push(
      `INSERT OR IGNORE INTO users (username, full_name, email, password_hash, is_admin, created_at)`,
      `VALUES (${q(spec.username)}, ${q(spec.fullName)}, ${q(`${spec.username}@codepr.local`)}, ${q(hash)}, ${spec.isAdmin ? 1 : 0}, ${q(now)});`,
      "",
    );

    for (const slug of spec.sites) {
      lines.push(
        `INSERT OR IGNORE INTO user_sites (user_id, site_id)`,
        `SELECT u.id, s.id FROM users u, sites s WHERE u.username = ${q(spec.username)} AND s.slug = ${q(slug)};`,
        "",
      );
    }

    created.push({ username: spec.username, password, isAdmin: spec.isAdmin });
  }

  writeFileSync(SQL_FILE, lines.join("\n"), { mode: 0o600 });

  // Credentials at rest: owner-readable only.
  const stamp = new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC";
  const secrets: string[] = [];
  if (!existsSync(SECRETS_FILE)) {
    secrets.push(
      "# CodePR-Monitor — Local Credentials",
      "",
      "Generated by `npm run seed`. This file is gitignored and must never be",
      "committed. These are local application accounts only; they are unrelated",
      "to Odoo or Cloudflare Access credentials.",
      "",
    );
  }
  secrets.push(
    `## Seeded ${stamp}`,
    "",
    "| Username | Password | Role |",
    "| --- | --- | --- |",
    ...created.map(
      (c) => `| \`${c.username}\` | \`${c.password}\` | ${c.isAdmin ? "Admin" : "Client"} |`,
    ),
    "",
  );
  appendFileSync(SECRETS_FILE, secrets.join("\n") + "\n");
  chmodSync(SECRETS_FILE, 0o600);

  const target = local ? "--local" : "--remote";
  console.log(`Wrote ${SQL_FILE}`);
  console.log(`Wrote ${SECRETS_FILE} (${created.length} credential(s))`);
  console.log("");
  console.log("Apply it with:");
  console.log(`  npx wrangler d1 execute cpr-monitor ${target} --file=seed.generated.sql`);
  console.log("");
  console.log("Then delete seed.generated.sql — the hashes are already in D1.");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
